coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default: false
      source:
        paths:
          - src/

comment:
  layout: "diff, flags, files"
  behavior: default  # update, if exists. Otherwise post new.
  require_changes: true  # only post the comment if coverage changes
  require_base: no
  require_head: yes

flags:
  unit:
    paths:
      - src/**/*.ts
  integration:
    paths:
      - src/**/*.ts

ignore:
  - "lib/*"
  - "script/*"
  - "test/**/*"
