# Check out depcheck at: https://github.com/depcheck/depcheck

ignores:
  - "@commitlint/*"
  - "@stryker-mutator/*"
  - "@types/*"
  - rollup
  - ts-jest
  - typescript
ignore-path: .gitignore
ignore-patterns:
  - lib/

parsers:
  "**/*.cjs": es6
  "**/*.js": es6
  "**/*.ts": typescript
