hooks:
  commit-msg: commitlint -E HUSKY_GIT_PARAMS
  pre-commit: >
    git stash -q --keep-index &&
    npm run format &&
    npm run build &&
    git checkout -- lib/.svgo.yml &&
    git checkout -- lib/index.js &&
    git update-index --again &&
    git stash pop -q
