name: 'SVGO action'
description: 'Automatically run SVGO on SVGs in Pull Requests'
author: 'Eric Cornelissen'

inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  configuration-path:
    description: 'The path for the svgo-action configurations'
    default: '.github/svgo-action.yml'
    required: false
  dry-run:
    description: 'Run the action in dry mode (i.e. do not commit)'
    default: false
    required: false
  svgo-options:
    description: 'The path of the configuration file for SVGO'
    default: '.svgo.yml'
    required: false

runs:
  using: 'node12'
  main: 'lib/index.js'

branding:
  icon: 'crop'
  color: 'blue'
