name: 'SVGO action'
description: 'Automatically run SVGO with GitHub Actions'
author: 'Eric Cornelissen'

inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  comment:
    description: 'Enable comments on Pull Requests with an optimization summary'
    default: false
    required: false
  configuration-path:
    description: 'The path for the svgo-action configurations'
    default: '.github/svgo-action.yml'
    required: false
  conventional-commits:
    description: 'Use conventional commit titles for commits'
    default: false
    required: false
  dry-run:
    description: 'Run the action in dry mode (i.e. do not commit)'
    default: false
    required: false
  ignore:
    description: 'A glob of SVGs that should not be optimized'
    default: ''
    required: false
  svgo-options:
    description: 'The path of the configuration file for SVGO'
    default: 'svgo.config.js'
    required: false
  svgo-version:
    description: 'The (major) SVGO version to be used (`1` or `2`)'
    default: 2
    required: false

runs:
  using: 'node12'
  main: 'lib/index.js'

branding:
  icon: 'crop'
  color: 'blue'
