#!/bin/sh
. "$(dirname $0)/_/husky.sh"
. "$(dirname $0)/common.sh"

if [ ! $(IS_MERGING) ]; then
  git stash push --quiet --include-untracked
fi

# Ensure tests and linting pass
npm run lint
npm run test:unit

if [ $(DID_STASH) ]; then
  git stash pop --quiet --index
fi
