#!/bin/sh
. "$(dirname $0)/_/husky.sh"
. "$(dirname $0)/common.sh"

if [ ! $(IS_MERGING) ]; then
  LIB_STAGED_COUNT=$(git diff --name-only --staged lib/ | wc -l)
  if [ "$LIB_STAGED_COUNT" -ne "0" ]; then
    echo "[INFO] All changes to the lib/ directory have been unstaged."
    echo "[INFO] Changes in the lib/ directory should not be committed."
    git restore --staged lib/
  fi

  git stash push --quiet --include-untracked --keep-index
fi

# Run vetting tools
npm run vet

# Run linters that don't support formatting
npm run lint:ws

# Format source code and update staged files
npm run format
git update-index --again

if [ $(DID_STASH) ]; then
  git stash pop --quiet
fi
