#!/bin/sh
. "$(dirname $0)/_/husky.sh"
. "$(dirname $0)/common.sh"

if [ ! $(IS_MERGING) ]; then
  git stash -q -u --keep-index
fi

# Format source code and update staged files
npm run format
git update-index --again

if [ $(DID_STASH) ]; then
  git stash pop -q
fi
