#!/bin/sh
. "$(dirname $0)/_/husky.sh"

# Stash unstaged files
git stash -q -u --keep-index

# Format source code and update staged files
npm run format
git update-index --again

# Restore unstaged files
git stash pop -q || true
