#!/bin/sh
. "$(dirname $0)/_/husky.sh"

# Stash unstaged files
git stash -q -u --keep-index

# Ensure tests and linting pass
npm run lint
npm run test:unit

# Restore unstaged files
git stash pop -q || true
