#!/bin/sh
. "$(dirname $0)/_/husky.sh"
. "$(dirname $0)/common.sh"

if [ ! $(IS_MERGING) ]; then
  git stash push --quiet --include-untracked
fi

# Ensure tests, linting, and vetting pass
npm run vet
npm run lint
npm run test:unit

if command -v shellcheck > /dev/null; then
  npm run lint:sh
fi

if [ $(DID_STASH) ]; then
  git stash pop --quiet --index
fi
