name: Config Codecov
on:
  pull_request:
    paths:
      - .github/workflows/config-codecov.yml
      - .github/codecov.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/config-codecov.yml
      - .github/codecov.yml

permissions: read-all

jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-22.04
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            actions-results-receiver-production.githubapp.com:443
            api.github.com:443
            codecov.io:443
            github.com:443
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Validate Codecov configuration
        uses: ericcornelissen/codecov-config-validator-action@bbb3f8ef45de6f6ce57ea8d566940bdd78b4814a # v1.0.2
