name: Labeler
on:
  pull_request_target: ~

permissions: read-all

jobs:
  label:
    name: Label
    permissions:
      pull-requests: write # To assign labels
    runs-on: ubuntu-22.04
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
      - name: Set labels on Pull Request
        uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594 # v4.3.0
        with:
          configuration-path: .github/labeler.yml
          sync-labels: ""
