name: Monthly
on:
  schedule:
    - cron: "0 2 23 * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  npm-deps:
    name: Update transitive dependencies
    runs-on: ubuntu-22.04
    permissions:
      contents: write # To push a commit
      pull-requests: write # To open a Pull Request
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            artifactcache.actions.githubusercontent.com:443
            github.com:443
            nodejs.org:443
            objects.githubusercontent.com:443
            registry.npmjs.org:443
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Create automation token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: automation-token
        with:
          app_id: ${{ secrets.AUTOMATION_APP_ID }}
          private_key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}
      - name: Install dependencies
        run: npm clean-install
      - name: Update dependencies
        run: npm update
      - name: Deduplicate dependencies
        run: npm dedupe
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          token: ${{ steps.automation-token.outputs.token }}
          title: Update transitive dependencies
          body: |
            _This Pull Request was created automatically_

            ---

            Update all transitive dependencies using `npm update` and `npm dedupe`.
          labels: dependencies
          branch: npm-update-transitive-deps
          commit-message: "chore(deps): update transitive dependencies"
          add-paths: |
            package.json
            package-lock.json
