name: Semgrep
on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-22.04
    permissions:
      security-events: write # To upload SARIF results
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Perform Semgrep analysis
        run: semgrep ci --sarif --output semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      - name: Upload Semgrep report to GitHub
        uses: github/codeql-action/upload-sarif@1b1aada464948af03b950897e5eb522f92603cc2 # v3.24.9
        if: ${{ failure() || success() }}
        with:
          sarif_file: semgrep.sarif
